
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "fix"
    target_branch: "dependa"
    default_reviewers:
      - Alexandrshy
